TrainingRegistrationScreen As screen:
    LoadingSpinnerColor: =RGBA(0, 120, 212, 1)

    conMain As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        c_ActionHeader_2 As groupContainer.verticalAutoLayoutContainer:
            Fill: =RGBA(243, 242, 241, 1)
            FillPortions: =0
            Height: =44
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutGap: =15
            LayoutJustifyContent: =LayoutJustifyContent.End
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =32
            PaddingRight: =32
            ZIndex: =1

            "inpSearchText As 'Fluent SearchBox (1.0.19) Preview'":
                AlignInContainer: =AlignInContainer.Center
                DisplayMode: =DisplayMode.Edit
                Height: =33
                LayoutMinHeight: =34
                LayoutMinWidth: =200
                PlaceHolderText: ="Search"
                Theme: =SearchBoxThemeJson
                Underlined: =true
                Width: =300
                X: =0
                Y: =0
                ZIndex: =3

            "chkOwned As 'Check box'":
                AccessibleLabel: ="Filter objects in which the logged-in user is an Owner."
                AlignInContainer: =AlignInContainer.Center
                Checked: =false
                DisplayMode: =DisplayMode.Edit
                Height: =32
                Label: ="Only owned apps"
                LayoutMinHeight: =32
                LayoutMinWidth: =160
                Visible: =false
                Width: =160
                X: =548
                Y: =73
                ZIndex: =4

        Header As groupContainer.verticalAutoLayoutContainer:
            FillPortions: =0
            Height: =160
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =40
            PaddingRight: =40
            PaddingTop: =32
            ZIndex: =2

            Label1 As Label:
                AutoHeight: =true
                DisplayMode: =DisplayMode.Edit
                FontSize: =16
                FontWeight: =FontWeight.Semibold
                Height: =43
                LayoutMinHeight: =32
                LayoutMinWidth: =320
                PaddingStart: =0  
                Text: ="My training events"
                Width: =320
                X: =35
                Y: =15
                ZIndex: =1

            lblTitle_5 As Label:
                AlignInContainer: =AlignInContainer.Stretch
                AutoHeight: =false
                Color: =    
                DisplayMode: =DisplayMode.View
                FontSize: =11
                FontWeight: =FontWeight.Normal
                Height: =80
                LayoutMinHeight: =80
                LayoutMinWidth: =320
                Text: ="View virtual or in-person training workshop you've registered for or cancel your registration."
                VerticalAlignment: =VerticalAlign.Top
                Width: =840
                Wrap: =true
                X: =0
                Y: =0
                ZIndex: =2

        cMain As groupContainer.verticalAutoLayoutContainer:
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =40
            ZIndex: =5

            "listMyEvents As 'Fluent Details List (1.0.19)'.pcfdataset":
                AlignInContainer: =AlignInContainer.Stretch
                columns_Items: |-
                    =Table(
                        {
                            ColName: "EventName",
                            ColDisplayName: "Name",
                            ColWidth: 200,
                            ColSortable: true,
                            ColIsBold: true,
                            ColResizable: true
                        },
                        {
                            ColName: "StartTime",
                            ColDisplayName: "Start Time",
                            ColWidth: 155,
                            ColSortable: true,
                            ColIsBold: false,
                            ColResizable: true
                        },
                        {
                            ColName: "EndTime",
                            ColDisplayName: "End Time",
                            ColWidth: 155,
                            ColSortable: true,
                            ColIsBold: false,
                            ColResizable: true
                        },
                        {
                            ColName: "Location",
                            ColDisplayName: "Location",
                            ColWidth: 200,
                            ColSortable: true,
                            ColIsBold: false,
                            ColResizable: true
                        },
                        {
                            ColName: "Expertise",
                            ColDisplayName: "Expertise level",
                            ColWidth: 150,
                            ColSortable: true,
                            ColIsBold: false,
                            ColResizable: true
                        },
                        {
                            ColName: "Product",
                            ColDisplayName: "Product",
                            ColWidth: 200,
                            ColSortable: true,
                            ColIsBold: false,
                            ColResizable: true
                        },
                        {
                            ColName: "view",
                            ColDisplayName: "View details",
                            ColCellType:"clickableimage",
                            ColWidth: 100
                    },
                        {
                            ColName: "cancel",
                            ColDisplayName: "Cancel Registration",
                            ColCellType:"link",
                            ColWidth: 130
                    }
                    )
                Compact: =false
                DisplayMode: =DisplayMode.Edit
                FillPortions: =1
                Height: =200
                Items: |-
                    =With(
                        {
                            mySearchText: Trim(inpSearchText.SearchText)
                        },Filter(col_mytrainings,Or(
                                IsBlank(mySearchText),
                                mySearchText in EventName)
                            ))
                LayoutMinHeight: =200
                LayoutMinWidth: =Min(Last(App.SizeBreakpoints).Value, Parent.Width)
                OnChange: |-
                    =If(Self.EventName="CellAction",
                    	UpdateContext({event: Self.EventColumn, selectedEvent: LookUp(col_mytrainings, InADayEventId = GUID(Self.EventRowKey)), showDialog: true})
                    )
                RaiseOnRowSelectionChangeEvent: =true
                RecordKey: ="InADayEventId"
                SelectionAlwaysVisible: =false
                SelectionType: ='''PowerCAT.FluentDetailsList.SelectionType'''.None
                SelectRowsOnFocus: =true
                Theme: =AppThemeJson
                Width: =200
                X: =0
                Y: =0
                ZIndex: =1

                cancel2 As pcfDataField.textualColumn:
                    FieldDisplayName: ="cancel"
                    FieldName: ="cancel"
                    FieldType: ="s"
                    FieldVariantName: ="textualColumn"
                    Order: =1
                    ZIndex: =5

                EndTime3 As pcfDataField.textualColumn:
                    FieldDisplayName: ="EndTime"
                    FieldName: ="EndTime"
                    FieldType: ="d"
                    FieldVariantName: ="textualColumn"
                    Order: =2
                    ZIndex: =6

                EventName4 As pcfDataField.textualColumn:
                    FieldDisplayName: ="EventName"
                    FieldName: ="EventName"
                    FieldType: ="s"
                    FieldVariantName: ="textualColumn"
                    Order: =3
                    ZIndex: =7

                Expertise3 As pcfDataField.textualColumn:
                    FieldDisplayName: ="Expertise"
                    FieldName: ="Expertise"
                    FieldType: ="s"
                    FieldVariantName: ="textualColumn"
                    Order: =4
                    ZIndex: =8

                Location6 As pcfDataField.textualColumn:
                    FieldDisplayName: ="Location"
                    FieldName: ="Location"
                    FieldType: ="s"
                    FieldVariantName: ="textualColumn"
                    Order: =5
                    ZIndex: =9

                Product3 As pcfDataField.textualColumn:
                    FieldDisplayName: ="Product"
                    FieldName: ="Product"
                    FieldType: ="s"
                    FieldVariantName: ="textualColumn"
                    Order: =6
                    ZIndex: =10

                StartTime4 As pcfDataField.textualColumn:
                    FieldDisplayName: ="StartTime"
                    FieldName: ="StartTime"
                    FieldType: ="d"
                    FieldVariantName: ="textualColumn"
                    Order: =7
                    ZIndex: =11

                view1 As pcfDataField.textualColumn:
                    FieldDisplayName: ="view"
                    FieldName: ="view"
                    FieldType: ="s"
                    FieldVariantName: ="textualColumn"
                    Order: =8
                    ZIndex: =12

                InADayEventId1 As pcfDataField.textualColumn:
                    FieldDisplayName: ="InADayEventId"
                    FieldName: ="InADayEventId"
                    FieldType: ="g"
                    FieldVariantName: ="textualColumn"
                    Order: =9
                    ZIndex: =13

    dgRegisterForEvent As Dialog:
        Buttons: |-
            =If(event = "cancel", 
            Table({Label: "Cancel registration", ButtonType:'''Microsoft.CoreControls.Button.ButtonType'''.Primary }))
        DialogHeight: =280
        DialogWidth: =450
        Fill: =dgRegisterForEvent.OverlayColor
        Height: =Parent.Height
        OnButtonSelect: |+
            =If( Self.SelectedButton.Label = "Cancel registration", 
                    Remove(InADayAttendees, Filter(col_mytrainings, 'Registered Event'.InADayEvent = selectedEvent.InADayEventId));
            Remove(col_mytrainings, Filter(col_mytrainings, 'Registered Event'.InADayEvent = selectedEvent.InADayEventId));
            );
            
            UpdateContext({showDialog: false})
            
        OnCloseSelect: |-
            =UpdateContext({showDialog: false})
        SubTitle: |-
            =Text(selectedEvent.StartTime, "ddd, mmm dd, yyyy hh:mm AM/PM") & " - " & Text(selectedEvent.EndTime, "ddd, mmm dd, yyyy hh:mm AM/PM")
        Theme: =AppTheme
        Title: =selectedEvent.EventName
        Visible: =showDialog
        Width: =Parent.Width
        ZIndex: =2

    conRegisterForEvent As groupContainer.verticalAutoLayoutContainer:
        Height: =dgRegisterForEvent.ContentHeight-50
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        PaddingLeft: =21
        PaddingRight: =10
        Visible: =showDialog
        Width: =dgRegisterForEvent.ContentWidth
        X: =dgRegisterForEvent.ContentX
        Y: =dgRegisterForEvent.ContentY+40
        ZIndex: =3

        lblEventDescription As Label:
            AlignInContainer: =AlignInContainer.Stretch
            AutoHeight: =true
            DisplayMode: =DisplayMode.Edit
            FillPortions: =1
            Height: =32
            LayoutMinHeight: =35
            LayoutMinWidth: =320
            PaddingStart: =0
            Text: =selectedEvent.EventDescription
            VerticalAlignment: =VerticalAlign.Top
            Width: =320
            X: =0
            Y: =0
            ZIndex: =1

        btnJoinTeams As Button:
            AlignInContainer: =AlignInContainer.Center
            DisplayMode: =DisplayMode.Edit
            Height: =32
            LayoutMinHeight: =32
            LayoutMinWidth: =96
            OnSelect: =Launch(selectedEvent.JoinLink)
            PaddingStart: =0
            Text: ="Join Microsoft Teams meeting"
            Visible: =!IsBlank(selectedEvent.JoinLink) && event = "view"
            Width: =250
            X: =0
            Y: =0
            ZIndex: =3

